function fixed = fixTableVariableNames(broken)

    if ~iscell(broken)
        broken = {broken}; 
        unCell = true; 
    else
        unCell = false;
    end

    replace = {...
        ' ',        '_'     ;...
        '-',        '_'     ;...
        '.',        '_'     ;...
        '>',        ''      ;...
        '<',        ''      ;...
        ':',        '_'     ;...
        '(',        ''      ;...
        ')',        ''      ;...
        '/',        '_'     ;...
        '&',        ''      ;...
        '|',        ''      ;...
        '°',        'deg'   ;...
        '?',        ''      ;...
        };
    
    for r = 1:length(replace)
        broken = strrep(broken, replace{r, 1}, replace{r, 2});
    end
    
    % find names starting with number
    firstNum = cellfun(@(x) ~isnan(str2double(x(1))), broken);
    broken(firstNum) = cellfun(@(x) ['V', x], broken(firstNum),...
        'uniform', false);
    
    % truncate long names
    tooLong = cellfun(@(x) length(x) > 63, broken);
    broken(tooLong) = cellfun(@(x) x(1:63), broken(tooLong),...
        'uniform', false);
    
    if unCell
        fixed = broken{:};
    else
        fixed = broken;
    end
    
end