Description of nt_cov
Home > NoiseTools > nt_cov.m
nt_cov
PURPOSE
[c,tw]=nt_cov(x,shifts,w) - time shift covariance
SYNOPSIS
function [c,tw]=nt_cov(x,shifts,w);
DESCRIPTION
[c,tw]=nt_cov(x,shifts,w) - time shift covariance
  c: covariance matrix
  tw: total weight (c/tw is normalized covariance)
  x: data
  shifts: array of time shifts (must be non-negative)
  w: weights
 If SHIFTS==[0], this function calculates the covariance matrix of X,
 weighted by W.  In the general case it calculates the covariance matrix
 of time-shifted X.
 X can be 1D, 2D or 3D.  It can also be a cell array.
 W can be 1D (if X is 1D or 2D) or 2D (if X is 3D). The same weight is
 applied to each column.
 Output is a 2D matrix with dimensions (ncols(X)*numel(SHIFTS))^2.
 It is made up of an ncols(X)*ncols(X) matrix of submatrices, each of
 dimensions numel(SHIFTS)*numel(SHIFTS).
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_multishift y=nt_multishift(x,shifts,pad) - apply multiple shifts to matrix
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_bias_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_bias_fft [c0,c1]=nt_bias_fft(x,freq,nfft) - covariance with and w/o filter bias
nt_bias_filter [c0,c1]=nt_bias_filter(x,B,A) - covariance with and w/o filter bias
nt_cca_aad [D,E,R]=nt_cca_match_aad(xA,xB,y,ssize) - calculate metrics for match-mismatch task
nt_cca_mm [D,E,R]=nt_cca_mm(x,y,ssize,ldaflag,nccs) - calculate metrics for match-mismatch task
nt_cca_mm3 [D,E,R]=nt_cca_mm(x,y,ssize,ldaflag,nccs) - calculate metrics for match-mismatch task
nt_cluster_jd [IDX,todss,SCORE,COVS]=nt_cluster_jd(x,dsr,smooth,flags,init,verbose) - cluster with joint diagonalization
nt_dprime [d,e]=nt_dprime(x,y,jd_flag) - calculate d' (discriminability) of two distributions
nt_dss1 [todss,pwr0,pwr1]=nt_dss1(x,w,keep1,keep2) - evoked-biased DSS denoising
nt_eyeblink [y,z,mask]=nt_eyeblink(x,eyechans,nremove) - project out eyeblinks
nt_lsp [Y,scores,removed]=nt_LSP(X,npass,thresh,tol,guard) - local subspace pruning
nt_pca [z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca0 [topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
nt_sca [M,y,score,proportion]=nt_sca(x,ncomp) - shared component analysis
nt_sns y=nt_sns(x,nneigbors,skip,w) - sensor noise suppression
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
nt_subspace_prune [Y]=nt_subspace_prune(X,npass,thresh) - local cleaning matrices
nt_subspace_prune5 [Y]=nt_subspace_prune(X,npass,thresh) - local cleaning matrices
nt_subspace_prune6 [Y]=nt_subspace_prune6(X,npass,thresh) - local cleaning matrices
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsr_nodemean [y,idx,w]=nt_tsr_nodemean(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
SOURCE CODE
function [c,tw]=nt_cov(x,shifts,w);
%[c,tw]=nt_cov(x,shifts,w) - time shift covariance
%
%  c: covariance matrix
%  tw: total weight (c/tw is normalized covariance)
%
%  x: data
%  shifts: array of time shifts (must be non-negative)
%  w: weights
%
% If SHIFTS==[0], this function calculates the covariance matrix of X,
% weighted by W.  In the general case it calculates the covariance matrix
% of time-shifted X.
%
% X can be 1D, 2D or 3D.  It can also be a cell array.
% W can be 1D (if X is 1D or 2D) or 2D (if X is 3D). The same weight is
% applied to each column.
%
% Output is a 2D matrix with dimensions (ncols(X)*numel(SHIFTS))^2.
% It is made up of an ncols(X)*ncols(X) matrix of submatrices, each of
% dimensions numel(SHIFTS)*numel(SHIFTS).
%
% NoiseTools
%% arguments
if nargin<3; w=[]; end;
if nargin<2||isempty(shifts); shifts=0; end;
if prod(size(x))==0; error('data empty'); end
shifts=shifts(:);           % --> column vector
nshifts=numel(shifts);
if isempty(x); error('data empty'); end
if isempty(w)
    %% no weights
    if isnumeric(x)
        %% matrix
        [m,n,o]=size(x);
        c=zeros(n*nshifts);
        for k=1:o
            xx=nt_multishift(x(:,:,k),shifts);
            c=c+xx'*xx;
        end
        tw=size(xx,1)*o;
    elseif iscell(x)
        %% cell array
        [m,n]=size(x{1});
        o=length(x);
        c=zeros(n*nshifts);
        for k=1:o;
            if size(x{k},2)~=n;  disp([size(x{k})]); disp([n, k]); error('!'); end
            xx=nt_multishift(x{k}(:,:),shifts);
            c=c+xx'*xx;
        end
        tw=size(xx,1)*o;
    else error('!'); end
else
    %% weights
    if isnumeric(x)
        %% matrix
        [m,n,o]=size(x);
        c=zeros(n*nshifts);
        for k=1:o
            if ~all(shifts == [0]);
                xx=nt_multishift(x(:,:,k),shifts);
                ww=nt_multishift(w(:,:,k),shifts);
                ww=min(ww,[],2);
            else
                xx=x(:,:,k); ww=w(:,:,k);
            end
            xx=nt_vecmult(xx,ww);
            c=c+xx'*xx;
        end
        tw=sum(w(:));
    else
        %% cell array
        c=zeros(n*nshifts);
        [m,n]=size(x{1});
        o=length(x);
        for k=1:o
            if ~all(shifts == [0]);
                xx=nt_multishift(x{k}(:,:),shifts);
                ww=nt_multishift(w{k}(:,:),shifts);
                ww=min(ww,[],2);
            else
                xx=x{k}(:,:); ww=w{k}(:,:);
            end
            xx=nt_vecmult(xx,ww);
            c=c+xx'*xx;
        end
        tw=sum(w(:));
    end
end